name: Clean Up Images

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  clean-ghcr:
    name: Clean up untagged images
    runs-on: ubuntu-latest
    steps:
      - name: Delete untagged images older than three days
        uses: snok/container-retention-policy@v2
        with:
          image-names: logto
          cut-off: Three days ago UTC
          account-type: org
          org-name: logto-io
          keep-at-least: 1
          untagged-only: true
          token: ${{ secrets.BOT_PAT }}
